In [1]:
import tensorflow as tf
from keras import layers


In [2]:
# 生成 10 个单词的数字编码
x = tf.range(10)
# 打散
x = tf.random.shuffle(x)
# 创建共 10 个单词，每个单词用长度为 4 的向量表示的层
net = layers.Embedding(10, 4)
# 获取词向量
out = net(x)

In [3]:
out

<tf.Tensor: shape=(10, 4), dtype=float32, numpy=
array([[-1.2001049e-02,  1.7076135e-03, -1.1047043e-02,  2.4659004e-02],
       [-4.9289893e-02,  4.0304545e-02, -4.5629408e-02, -4.9651336e-02],
       [-1.9313229e-02, -3.0124569e-02, -2.6360869e-02, -3.7404522e-03],
       [-5.3828582e-03, -4.1696168e-02,  9.4142072e-03,  3.9663043e-02],
       [-3.4599327e-02, -3.4740698e-02,  4.1285489e-02, -3.3653818e-02],
       [-2.5336862e-02,  6.1896443e-03, -2.5884867e-02, -4.7768224e-02],
       [-1.0702983e-03,  2.1191016e-03, -1.9161059e-02, -4.3287635e-02],
       [-1.6648412e-02, -4.2978253e-02, -2.5836170e-02,  1.4533997e-03],
       [-3.6909949e-02, -3.8839020e-02, -4.0508736e-02, -2.8179634e-02],
       [-5.8244914e-05,  1.2973476e-02, -8.7022781e-04,  1.8582676e-02]],
      dtype=float32)>

In [5]:
net.embeddings

<tf.Variable 'embedding/embeddings:0' shape=(10, 4) dtype=float32, numpy=
array([[-1.9313229e-02, -3.0124569e-02, -2.6360869e-02, -3.7404522e-03],
       [-1.0702983e-03,  2.1191016e-03, -1.9161059e-02, -4.3287635e-02],
       [-2.5336862e-02,  6.1896443e-03, -2.5884867e-02, -4.7768224e-02],
       [-4.9289893e-02,  4.0304545e-02, -4.5629408e-02, -4.9651336e-02],
       [-3.6909949e-02, -3.8839020e-02, -4.0508736e-02, -2.8179634e-02],
       [-5.3828582e-03, -4.1696168e-02,  9.4142072e-03,  3.9663043e-02],
       [-3.4599327e-02, -3.4740698e-02,  4.1285489e-02, -3.3653818e-02],
       [-1.6648412e-02, -4.2978253e-02, -2.5836170e-02,  1.4533997e-03],
       [-5.8244914e-05,  1.2973476e-02, -8.7022781e-04,  1.8582676e-02],
       [-1.2001049e-02,  1.7076135e-03, -1.1047043e-02,  2.4659004e-02]],
      dtype=float32)>

In [6]:
net.embeddings.trainable

True

In [ ]:
load_embed()